trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  dockerComposeFile: 'azurepipeline/docker-compose.yml'
  additionalDockerComposeFiles: 'azurepipeline/docker-compose-override.yml'
  azureSubscriptionEndpoint: azure_service_connection
  azureContainerRegistry: myazurepipelinedemoRG
  helloWorldWebImageName: myazurepipelinedemoregistry.azurecr.io/helloworldweb:v1
  helloWorldServiceImageName: myazurepipelinedemoregistry.azurecr.io/helloworldservice:v1
  dockerLoginId: myazurepipelinedemoregistry
  dockerPassword: tMxtMlPTQw9mw/FO2PPSk5i7z7NBzw3k
  registryServer: myazurepipelinedemoregistry.azurecr.io


steps:
- task: DockerInstaller@0
  displayName:  'Docker Installer'
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable

- script: |
    docker-compose -f $(dockerComposeFile) -f $(additionalDockerComposeFiles) up -d
  displayName: 'Build docker image'

- script: |
    docker login -u $(dockerLoginId) -p "tMxtMlPTQw9mw/FO2PPSk5i7z7NBzw3k" $(registryServer)
    docker push $(helloWorldWebImageName)
    docker push $(helloWorldServiceImageName)
  displayName: 'Push docker image to ACR'

